sonar.projectKey=veterinaria-backend
sonar.projectName=Veterinaria Backend
sonar.sourceEncoding=UTF-8

sonar.sources=backend/src/main/java
sonar.tests=backend/src/test/java

sonar.java.source=21
sonar.java.binaries=backend/target/classes
sonar.java.test.binaries=backend/target/test-classes

sonar.junit.reportPaths=backend/target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
